# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2
import easyocr
import numpy as np
import requests

# Projenin son hali buydu output.pyden değişimlere başlıyorum artık bir hata yaşanırsa buraya dönerim

reader = easyocr.Reader(['en'])

# pytesseract.pytesseract.tesseract_cmd = r'C:\Users\berat\AppData\Local\Programs\Tesseract-OCR\tesseract'

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage
from PyQt5.QtWidgets import QFileDialog, QMessageBox

BASE_URL = "http://localhost:8000/api"
API_KEY = "29b068e5f73f77da112c8aa6435993bb"


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1298, 653)
        MainWindow.setStyleSheet("background-color: #1e293b")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gb_otoparkBilgileri = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_otoparkBilgileri.setGeometry(QtCore.QRect(10, 10, 621, 291))
        self.gb_otoparkBilgileri.setStyleSheet("background-color: rgb(15, 23, 42);\n"
                                               "font: 600 10pt \"Segoe UI\";\n"
                                               "border:0;\n"
                                               "border-radius:5px;\n"
                                               "color: rgb(240, 245, 245);\n"
                                               "\n"
                                               "")
        self.gb_otoparkBilgileri.setObjectName("gb_otoparkBilgileri")
        self.layoutWidget = QtWidgets.QWidget(parent=self.gb_otoparkBilgileri)
        self.layoutWidget.setGeometry(QtCore.QRect(270, 50, 321, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lb_kapiDurumu = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lb_kapiDurumu.setStyleSheet("border-radius:0px;\n"
                                         "border-bottom:1px solid gray;\n"
                                         "font-weight:700;\n"
                                         "font-size:20px")
        self.lb_kapiDurumu.setObjectName("lb_kapiDurumu")
        self.verticalLayout_5.addWidget(self.lb_kapiDurumu)
        self.lb_aracSayisi = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lb_aracSayisi.setStyleSheet("border-radius:0px;\n"
                                         "border-bottom:1px solid gray;\n"
                                         "font-weight:700;\n"
                                         "font-size:20px")
        self.lb_aracSayisi.setObjectName("lb_aracSayisi")
        self.verticalLayout_5.addWidget(self.lb_aracSayisi)
        self.lb_yanginAlarmi = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lb_yanginAlarmi.setStyleSheet("border-radius:0px;\n"
                                           "border-bottom:1px solid gray;\n"
                                           "font-weight:700;\n"
                                           "font-size:20px")
        self.lb_yanginAlarmi.setObjectName("lb_yanginAlarmi")
        self.verticalLayout_5.addWidget(self.lb_yanginAlarmi)
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_10.setStyleSheet("border-radius:0px;\n"
                                    "border-bottom:1px solid gray;\n"
                                    "font-weight:700;\n"
                                    "font-size:20px")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_12.setStyleSheet("border-radius:0px;\n"
                                    "padding-left:2px;\n"
                                    "font-weight:700;\n"
                                    "font-size:20px")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.widget = QtWidgets.QWidget(parent=self.gb_otoparkBilgileri)
        self.widget.setGeometry(QtCore.QRect(30, 50, 201, 221))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setStyleSheet("border-radius:0px;\n"
                                   "border-bottom:1px solid gray;\n"
                                   "font-weight:600;\n"
                                   "font-size:20px")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setStyleSheet("border-radius:0px;\n"
                                   "border-bottom:1px solid gray;\n"
                                   "font-weight:600;\n"
                                   "font-size:20px")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setStyleSheet("border-radius:0px;\n"
                                   "border-bottom:1px solid gray;\n"
                                   "font-weight:600;\n"
                                   "font-size:20px")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setStyleSheet("border-radius:0px;\n"
                                   "border-bottom:1px solid gray;\n"
                                   "font-weight:600;\n"
                                   "font-size:20px")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(parent=self.widget)
        self.label_11.setStyleSheet("border-radius:0px;\n"
                                    "padding-left:2px;\n"
                                    "font-weight:600;\n"
                                    "font-size:20px")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.gb_kamera = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_kamera.setGeometry(QtCore.QRect(660, 10, 611, 291))
        self.gb_kamera.setStyleSheet("background-color: rgb(15, 23, 42);\n"
                                     "font: 600 10pt \"Segoe UI\";\n"
                                     "border:0;\n"
                                     "border-radius:5px;\n"
                                     "color: rgb(240, 245, 245);\n"
                                     "\n"
                                     "\n"
                                     "")
        self.gb_kamera.setObjectName("gb_kamera")
        self.lb_kamera = QtWidgets.QLabel(parent=self.gb_kamera)
        self.lb_kamera.setGeometry(QtCore.QRect(10, 30, 591, 251))
        self.lb_kamera.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lb_kamera.setText("")
        self.lb_kamera.setPixmap(QtGui.QPixmap("cars/mercedes.jpg"))
        self.lb_kamera.setObjectName("lb_kamera")
        self.gb_sistemKontrol = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_sistemKontrol.setGeometry(QtCore.QRect(10, 320, 621, 291))
        self.gb_sistemKontrol.setStyleSheet("background-color: rgb(15, 23, 42);\n"
                                            "font: 600 10pt \"Segoe UI\";\n"
                                            "border:0;\n"
                                            "border-radius:5px;\n"
                                            "color: rgb(240, 245, 245);\n"
                                            "")
        self.gb_sistemKontrol.setObjectName("gb_sistemKontrol")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.gb_sistemKontrol)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 231, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_plakaNo = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.le_plakaNo.setStyleSheet("border-radius: 4px;\n"
                                      "border: 1px solid #e0e4e7;\n"
                                      "padding: 3px 5px;\n"
                                      "background-color:#e2e8f0;\n"
                                      "color:#0f172a;\n"
                                      "letter-spacing:2px")
        self.le_plakaNo.setObjectName("le_plakaNo")
        self.horizontalLayout.addWidget(self.le_plakaNo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton.setStyleSheet("border: 1px solid #81E6D9;\n"
                                      "border-radius: 5px;\n"
                                      "padding: 6px 0px;\n"
                                      "color:#81E6D9;\n"
                                      "font: 700 10pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.btn_aracSec = QtWidgets.QPushButton(parent=self.gb_sistemKontrol)
        self.btn_aracSec.setGeometry(QtCore.QRect(460, 20, 151, 41))
        self.btn_aracSec.setStyleSheet("border: 2px solid #81E6D9;\n"
                                       "border-radius: 8px;\n"
                                       "padding: 8px 4px;\n"
                                       "color:#81E6D9;\n"
                                       "font: 700 9pt \"Segoe UI\";")
        self.btn_aracSec.setObjectName("btn_aracSec")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.gb_sistemKontrol)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 170, 231, 103))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_kapiyiAc = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.btn_kapiyiAc.setStyleSheet("border: 2px solid #81E6D9;\n"
                                        "border-radius: 8px;\n"
                                        "padding: 8px 4px;\n"
                                        "color:#81E6D9;\n"
                                        "font: 700 9pt \"Segoe UI\";")
        self.btn_kapiyiAc.setObjectName("btn_kapiyiAc")
        self.verticalLayout_3.addWidget(self.btn_kapiyiAc)
        self.btn_kapiyiKapat = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.btn_kapiyiKapat.setStyleSheet("border: 2px solid #81E6D9;\n"
                                           "border-radius: 8px;\n"
                                           "padding: 8px 4px;\n"
                                           "color:#81E6D9;\n"
                                           "font: 700 9pt \"Segoe UI\";")
        self.btn_kapiyiKapat.setObjectName("btn_kapiyiKapat")
        self.verticalLayout_3.addWidget(self.btn_kapiyiKapat)
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.gb_sistemKontrol)
        self.layoutWidget3.setGeometry(QtCore.QRect(410, 170, 201, 111))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_sistemiBaslat = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.btn_sistemiBaslat.setStyleSheet("border: 2px solid #4ade80;\n"
                                             "border-radius: 8px;\n"
                                             "padding: 8px 4px;\n"
                                             "color:#4ade80;\n"
                                             "font: 700 9pt \"Segoe UI\";")
        self.btn_sistemiBaslat.setObjectName("btn_sistemiBaslat")
        self.verticalLayout_6.addWidget(self.btn_sistemiBaslat)
        self.btn_sistemiKapat = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.btn_sistemiKapat.setStyleSheet("border: 2px solid #f43f5e;\n"
                                            "border-radius: 8px;\n"
                                            "padding: 8px 4px;\n"
                                            "color:#f43f5e;\n"
                                            "font: 700 9pt \"Segoe UI\";")
        self.btn_sistemiKapat.setObjectName("btn_sistemiKapat")
        self.verticalLayout_6.addWidget(self.btn_sistemiKapat)
        self.widget1 = QtWidgets.QWidget(parent=self.gb_sistemKontrol)
        self.widget1.setGeometry(QtCore.QRect(410, 120, 201, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(parent=self.widget1)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.comboBox = QtWidgets.QComboBox(parent=self.widget1)
        self.comboBox.setStyleSheet("background-color:#fff;\n"
                                    "color:black")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.gb_aracBilgileri = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_aracBilgileri.setGeometry(QtCore.QRect(660, 320, 611, 291))
        self.gb_aracBilgileri.setStyleSheet("background-color: rgb(15, 23, 42);\n"
                                            "font: 600 10pt \"Segoe UI\";\n"
                                            "border:0;\n"
                                            "border-radius:5px;\n"
                                            "color: rgb(240, 245, 245);\n"
                                            "")
        self.gb_aracBilgileri.setObjectName("gb_aracBilgileri")
        self.widget2 = QtWidgets.QWidget(parent=self.gb_aracBilgileri)
        self.widget2.setGeometry(QtCore.QRect(10, 40, 179, 231))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(parent=self.widget2)
        self.label_3.setStyleSheet("border-radius:0px;\n"
                                   "border-bottom:1px solid gray;\n"
                                   "padding: 0px 25px;\n"
                                   "font-size:22px;\n"
                                   "text-align:center")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.label_13 = QtWidgets.QLabel(parent=self.widget2)
        self.label_13.setStyleSheet("border-radius:0px;\n"
                                    "border-bottom:1px solid gray;\n"
                                    "padding: 0px 25px;\n"
                                    "font-size:22px;\n"
                                    "text-align:center")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.label_2 = QtWidgets.QLabel(parent=self.widget2)
        self.label_2.setStyleSheet("border-radius:0px;\n"
                                   "border-bottom:1px solid gray;\n"
                                   "padding: 0px 25px;\n"
                                   "font-size:22px;\n"
                                   "")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(parent=self.widget2)
        self.label_4.setStyleSheet("border-radius:0px;\n"
                                   "border-bottom:1px solid gray;\n"
                                   "padding: 0px 25px;\n"
                                   "font-size:22px;\n"
                                   "")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.widget2)
        self.label_5.setStyleSheet("border-radius:0px;\n"
                                   "padding: 0px 25px;\n"
                                   "font-size:22px;\n"
                                   "")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.widget3 = QtWidgets.QWidget(parent=self.gb_aracBilgileri)
        self.widget3.setGeometry(QtCore.QRect(210, 40, 361, 231))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lb_uyeID = QtWidgets.QLabel(parent=self.widget3)
        self.lb_uyeID.setStyleSheet("border-radius:0px;\n"
                                    "border-bottom:1px solid gray;\n"
                                    "padding: 0px 20px;\n"
                                    "font-size:22px;\n"
                                    "letter-spacing:1px")
        self.lb_uyeID.setObjectName("lb_uyeID")
        self.verticalLayout_4.addWidget(self.lb_uyeID)
        self.lb_aracPlaka = QtWidgets.QLabel(parent=self.widget3)
        self.lb_aracPlaka.setStyleSheet("border-radius:0px;\n"
                                        "border-bottom:1px solid gray;\n"
                                        "padding: 0px 20px;\n"
                                        "font-size:22px;\n"
                                        "letter-spacing:1px")
        self.lb_aracPlaka.setObjectName("lb_aracPlaka")
        self.verticalLayout_4.addWidget(self.lb_aracPlaka)
        self.lb_aracSahibi = QtWidgets.QLabel(parent=self.widget3)
        self.lb_aracSahibi.setStyleSheet("border-radius:0px;\n"
                                         "border-bottom:1px solid gray;\n"
                                         "padding: 0px 20px;\n"
                                         "font-size:22px;\n"
                                         "letter-spacing:1px")
        self.lb_aracSahibi.setObjectName("lb_aracSahibi")
        self.verticalLayout_4.addWidget(self.lb_aracSahibi)
        self.lb_girisSaati = QtWidgets.QLabel(parent=self.widget3)
        self.lb_girisSaati.setStyleSheet("border-radius:0px;\n"
                                         "border-bottom:1px solid gray;\n"
                                         "padding: 0px 20px;\n"
                                         "font-size:22px;\n"
                                         "letter-spacing:1px")
        self.lb_girisSaati.setObjectName("lb_girisSaati")
        self.verticalLayout_4.addWidget(self.lb_girisSaati)
        self.lb_cikisSaati = QtWidgets.QLabel(parent=self.widget3)
        self.lb_cikisSaati.setStyleSheet("border-radius:0px;\n"
                                         "padding: 0px 20px;\n"
                                         "font-size:22px;\n"
                                         "letter-spacing:1px")
        self.lb_cikisSaati.setObjectName("lb_cikisSaati")
        self.verticalLayout_4.addWidget(self.lb_cikisSaati)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Butonların fonksiyon bağlantıları
        self.btn_aracSec.clicked.connect(self.loadImage)
        self.pushButton.clicked.connect(self.manuelAracGiris)
        self.btn_sistemiKapat.clicked.connect(self.CloseTheSystem)
        self.btn_kapiyiAc.clicked.connect(self.OpenTheDoor)
        self.btn_kapiyiKapat.clicked.connect(self.CloseTheDoor)
        self.btn_sistemiBaslat.clicked.connect(self.StartTheSystem)

    def ShowMessage(self, status, text, title):
        msgBox = QMessageBox()
        msgBox.setIcon(status)
        msgBox.setText(text)
        msgBox.setWindowTitle(title)
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.setDefaultButton(QMessageBox.Ok)
        returnValue = msgBox.exec()
        return returnValue

    def manuelAracGiris(self):
        plaka = self.le_plakaNo.text()
        if plaka:
            self.aracGirisiYap(plaka)
        else:
            print("Plaka Giriniz.")

    # kapı fonksiyonları
    def OpenTheDoor(self):
        print("Kapı açılacak...")

    def CloseTheDoor(self):
        print("Kapı Kapanacak...")

    # sistem fonksiyonları
    def StartTheSystem(self):
        print("Sistem başlatılıyor...")

    def CloseTheSystem(self):
        print("Sistem kapatılıyor...")
        MainWindow.close()

    # resim seçme fonksiyonları
    def loadImage(self):
        try:
            file_name = QFileDialog.getOpenFileName(filter="Image (*.*)")[0]
            image = cv2.imread(file_name)
            setImage = cv2.resize(image, (591, 251))
            self.setPhoto(setImage)
            self.definePlate(image)
        except:
            self.ShowMessage(QMessageBox.Warning, "Resim Yüklenirken Hata Oluştu.", "Uyarı")

    def setPhoto(self, image):
        try:
            frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = QImage(frame, frame.shape[1], frame.shape[0], frame.strides[0], QImage.Format_RGB888)
            self.lb_kamera.setPixmap(QtGui.QPixmap.fromImage(image))

        except:
            self.ShowMessage(QMessageBox.Warning, "Resim Değiştirilirken Hata Oluştu.", "Uyarı")

    """
    # plakayı tanımlama fonksiyonu
    def definePlate(self, image):

        try:
            # plaka araçların alt kısmında bulunduğu için resmin yukarda kalan kısmını kırptım.



            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

            # filtre için ideal değerler [7,9]-75-75
            # resmin kenarlarını bulmadan önce gürültülerden kurtuluyoruz
            filter = cv2.bilateralFilter(gray, 7, 75, 75)

            # canny için ideal değerler 50-200
            edges = cv2.Canny(filter, 50, 200)

            contours = cv2.findContours(edges, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
            # bulunan kontürleri numpy array'ine çevirdik
            contours = imutils.grab_contours(contours)
            # En iyi 20 konturu bulduk
            contours = sorted(contours, key=cv2.contourArea, reverse=True)

            border = None
            for contour in contours:
                epsilon = 0.012 * cv2.arcLength(contour, True)
                approx = cv2.approxPolyDP(contour, epsilon, True)
                # 4 kenarlı bir şekil bulduğumuzda duruyoruz.
                if len(approx) == 4:
                    border = approx
                    break

            # resmin boyutu kadar siyah bir filtre oluşturduk
            maske = np.zeros(gray.shape, np.uint8)

            # önceden oluşturduğumuz siyah filtrenin border bölgesini beyaza boyuyoruz.
            cv2.drawContours(maske, [border], 0, (255, 255, 255), -1)

            filteredPlate = cv2.bitwise_and(image, image, mask=maske)

            # cv2.imshow("FilteredPlate", filteredPlate)

            (x, y) = np.where(maske == 255)
            (x_min, y_min) = (np.min(x), np.min(y))
            (x_max, y_max) = (np.max(x), np.max(y))

            # ROI (kırpma işlemi)
            correctPlate = image[x_min:x_max, y_min:y_max]

            # Resimden plaka okuma
            results = reader.readtext(correctPlate, decoder="beamsearch", blocklist=" ",
                                      allowlist="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")

            bestMatch = ""
            if results:
                for i in range(len(results)):
                    text = results[i][1]
                    accuracy = results[i][2]
                    print(text, accuracy)
                    if accuracy > 0.60:
                        bestMatch += text
            else:
                print("easocr error")

            #cv2.imshow("Filtre", filter)
            #cv2.imshow("Canny", edges)
            #cv2.imshow("maske", maske)
            cv2.imshow("filteredPlate", filteredPlate)
            #cv2.imshow("image",image)

            print("plaka:", bestMatch)

            if bestMatch:
                self.aracGirisiYap(bestMatch)
            # cv2.imshow("currentPlate", correctPlate)
            cv2.waitKey(0)

        except:
            self.ShowMessage(QMessageBox.Warning, "Plakayı okurken hata oluştu.", "Uyarı")

        finally:
            cv2.destroyAllWindows()
    """

    def definePlate(self, image):
        try:
            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

            filter = cv2.bilateralFilter(gray, 7, 75, 75)

            edges = cv2.Canny(filter, 50, 300)

            contours, _ = cv2.findContours(edges, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

            contours = sorted(contours, key=cv2.contourArea, reverse=True)[:50]
            border = None

            # Plaka bölgelerini bul
            plate_contours = []

            for contour in contours:

                epsilon = 0.012 * cv2.arcLength(contour, True)

                approx = cv2.approxPolyDP(contour, epsilon, True)

                if len(approx) == 4:

                    x, y, width, height = cv2.boundingRect(contour)
                    aspect_ratio = width / float(height)

                    area = cv2.contourArea(contour)

                    # Belirli boyut ve oran kriterlerine göre filtreleme yap
                    if 1500 < area < 50000 and 2.8 <= aspect_ratio <= 5.5:
                        plate_contours.append(contour)

            for contour in plate_contours:
                x, y, w, h = cv2.boundingRect(contour)
                cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)

            """
            maske = np.zeros(gray.shape, np.uint8)
            cv2.drawContours(maske, [border], 0, (255, 255, 255), -1)

            filteredPlate = cv2.bitwise_and(image, image, mask=maske)

            (x, y) = np.where(maske == 255)
            (x_min, y_min) = (np.min(x), np.min(y))
            (x_max, y_max) = (np.max(x), np.max(y))

            # ROI (kırpma işlemi)
            correctPlate = image[x_min:x_max, y_min:y_max]


            bestMatch = ""
            if bestMatch:
                self.aracGirisiYap(bestMatch)
            """
            cv2.imshow("image", image)
        except:
            self.ShowMessage(QMessageBox.Warning, "Plakayı okurken hata oluştu.", "Uyarı")

    # arac girisi kontrol fonksiyonu
    def aracGirisiYap(self, plaka):

        try:
            response = requests.get(BASE_URL + "/customers/find?plate=" + plaka + "&api_key=" + API_KEY)
            customer = response.json()
            if customer["success"]:
                parkData = {
                    "plate": plaka,
                    "customerId": customer["customer"][0]["_id"]
                }
                response = requests.post(BASE_URL + "/parks/new", parkData)
                data = response.json()
                print(data)
                if data["success"]:
                    girisSaati = data["park"]["entry_time"]
                    # girisSaatini okunabilir bir saate dönüştürdükten sonra yazdırıcam.
                    self.lb_uyeID.setText(customer["customer"][0]["_id"])
                    self.lb_aracPlaka.setText(customer["customer"][0]["plate"])
                    self.lb_aracSahibi.setText(customer["customer"][0]["fullName"])
                    self.lb_girisSaati.setText(girisSaati)
                    self.lb_cikisSaati.setText("--:--")
                    self.ShowMessage(QMessageBox.Information, data["message"], "Başarılı.")

                else:
                    self.ShowMessage(QMessageBox.Warning, data["error"], "Hata!")


            else:
                returnValue = self.ShowMessage(QMessageBox.Warning, "Plaka Sisteme Kayıtlı Değil.", "Uyarı")
                if returnValue == QMessageBox.Ok:
                    print('OK clicked')

        except:
            returnValue = self.ShowMessage(QMessageBox.Critical, "Araç Girişinde Bir Hata Oluştu.", "Uyarı")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gb_otoparkBilgileri.setTitle(_translate("MainWindow", "Otopark Bilgileri"))
        self.lb_kapiDurumu.setText(_translate("MainWindow", "Kapalı"))
        self.lb_aracSayisi.setText(_translate("MainWindow", "9/32"))
        self.lb_yanginAlarmi.setText(_translate("MainWindow", "Yok"))
        self.label_10.setText(_translate("MainWindow", "12:43:53"))
        self.label_12.setText(_translate("MainWindow", "03/29/2023"))
        self.label_6.setText(_translate("MainWindow", "Kapı Durumu:"))
        self.label_7.setText(_translate("MainWindow", "Araç Sayısı:"))
        self.label_8.setText(_translate("MainWindow", "Yangın Durumu:"))
        self.label_9.setText(_translate("MainWindow", "Saat:"))
        self.label_11.setText(_translate("MainWindow", "Tarih:"))
        self.gb_kamera.setTitle(_translate("MainWindow", "Kamera Görüntüsü"))
        self.gb_sistemKontrol.setTitle(_translate("MainWindow", "Sistem Kontrol"))
        self.label.setText(_translate("MainWindow", "Plaka No:"))
        self.le_plakaNo.setText(_translate("MainWindow", "34ABC562"))
        self.pushButton.setText(_translate("MainWindow", "Araç Girişi Yap"))
        self.btn_aracSec.setText(_translate("MainWindow", "Arac Sec"))
        self.btn_kapiyiAc.setText(_translate("MainWindow", "Kapıyı Aç "))
        self.btn_kapiyiKapat.setText(_translate("MainWindow", "Kapıyı Kapat"))
        self.btn_sistemiBaslat.setText(_translate("MainWindow", "Sistemi Başlat"))
        self.btn_sistemiKapat.setText(_translate("MainWindow", "Sistemi Kapat"))
        self.label_14.setText(_translate("MainWindow", "PORT:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "COM3"))
        self.comboBox.setItemText(1, _translate("MainWindow", "COM4"))
        self.comboBox.setItemText(2, _translate("MainWindow", "COM5"))
        self.gb_aracBilgileri.setTitle(_translate("MainWindow", "Araç Bilgileri"))
        self.label_3.setText(_translate("MainWindow", "Üye ID:"))
        self.label_13.setText(_translate("MainWindow", "Plaka:"))
        self.label_2.setText(_translate("MainWindow", "Araç Sahibi:"))
        self.label_4.setText(_translate("MainWindow", "Giriş Saati:"))
        self.label_5.setText(_translate("MainWindow", "Çıkış Saati:"))
        self.lb_uyeID.setText(_translate("MainWindow", "2165486854646"))
        self.lb_aracPlaka.setText(_translate("MainWindow", "34 ABC 556"))
        self.lb_aracSahibi.setText(_translate("MainWindow", "Berat Hazer"))
        self.lb_girisSaati.setText(_translate("MainWindow", "15 : 03"))
        self.lb_cikisSaati.setText(_translate("MainWindow", "19 : 30"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
